# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 65fdac7290e8cb05c89468c9745699e6f31534a48bb86601396d0c70b8063e29c1fbe476261e401f95c3940040abc1a7eafa6df8fd2fb6225cdfccf1909f9c86

test:
  secret_key_base: 6fb93eeba714e05e3396ee0d4c1d6bdd4f77c011ebbb53b755b51a3a7cee2f2288296febc08a0aad703408b8fe88d914f5043282e7df805e5162818ba5dadc11

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
